Use default config and copy in-place at first run
bionade24/aur-ci pull request #4
Opened 2020-08-01 07:36 UTC by fmauch

This way, an added OAUTH token will not show up as modification inside the git index.

Otherwise this makes many git operations a bit impractical, as e.g. rebasing
requires a clean index. Also, this should prevent users from accidentally
adding their token to the vcs.

2020-08-01 14:13 UTC, bionade24 requested changes
Ok, I just executed  `git update-index --skip-worktree config.ini` once and then never cared about it. Glad you did. But I think`config_example.ini` would be a more self-explaining name than `config_distribute.ini`. And please update the `requirements.txt` and add `shutil`.

2020-08-02 14:05 UTC, fmauch commented
Actually, regarding the `requirements.txt`: Is it necessary to add shutil, as it is a standard library?

2020-08-03 20:31 UTC, bionade24 approved these changes

2020-08-03 20:33 UTC, bionade24 commented
Sorry, my bad, then of course pip will complain during installation of `shutil`. My bad, should learn the standard library for python once.

2020-08-03 20:35 UTC, merged